version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/themes/advanced/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/themes/amaranth/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/examples/advanced-demo/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/examples/amaranth-demo/"
    schedule:
      interval: "monthly"
